### ISSUE TITLE
Add start and end times to the return from AOI_seq

### ISSUE THREAD

**Issue by tombeesley** [tombeesley/eyetools#16]
It would probably be useful to have a list of start and end times for the return from AOI_seq, much like with the fixation algorithms, which would then be useful in future visualisations

**Comment by M1V0** [comment]
Non-trivial request that would require a complete function overhaul. Is there any need to keep the option for having data in the original (long = FALSE) format? This is the sticking point for including this feature

**Comment by M1V0** [comment]
Completed in 0.7.3 commit #3095354
