### ISSUE TITLE
hdf5_to_csv function dataframe does not include messages sent to ioServer

### ISSUE THREAD

**Issue by munizdiezclara** [tombeesley/eyetools#18]
When running an eyetracking experiment in PsychoPy, a way of keeping track of the events that are happening in the experiment (and thus being able to track what is happening in the eyetracking file) is sending a message to teh ioServer that is written in one of the files within the hdf5 file, the MessageEvent file. 
However, the hdf5_to_csv function only reads the eyetracking file (I'm assuming either BinocularEyeSampleEvent or the MonocularEyeSampleEvent), so this information sent to the server gets lost, and would have to be extracted using the Python based code that PyschoPy provides for dealing with eyetracking data.

**Comment by M1V0** [comment]
Hi Clara, currently in development (branch 0.7.3.9000) is the function `hdf5_get_event()` which pulls the messages. Let me know if this serves your need.

**Comment by tombeesley** [comment]
Clara - you can install this with `devtools::install_github("tombeesley/eyetools@0.7.3.9000")`
