### ISSUE TITLE
AOI_seq documentation 

### ISSUE THREAD

**Issue by amy-atkinson** [tombeesley/eyetools#3]
The AOI_seq documentation states that the user should input "data", but this needs to be inputted as "fix_data" or "raw_data" (which is how AOI_time is described in the documentation).

**Comment by tombeesley** [comment]
I may have corrected this and not updated this issue. As it stands now, the function handles the data in the same way, whether it is fixations or raw data. So the user doesn't actually need to specify if it's fixation data or raw data. So `data = ` can be used in both cases.
